# Generated by Django 6.1 on 2026-08-31 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytics',
            old_name='data',
            new_name='date',
        ),
    ]
