import { useEffect, useState } from "react"
import client from "../../api/client"
import { Card, CardContent, CardHeader, CardTitle } from "../../components/ui/card"
import { Button } from "../../components/ui/button"
import { Input, Label } from "../../components/ui/input"

export default function AdminAnalytics() {
  const [snapshots, setSnapshots] = useState([])
  const [form, setForm] = useState({ date: new Date().toISOString().split("T")[0] })
  const [msg, setMsg] = useState("")
  const [error, setError] = useState("")

  const fetch = async () => {
    try {
      const res = await client.get("/analytics/")
      setSnapshots(Array.isArray(res.data)?res.data:res.data.results||[])
    } catch {}
  }
  useEffect(()=>{ fetch() }, [])

  const create = async (e) => {
    e.preventDefault()
    setMsg(""); setError("")
    try {
      await client.post("/analytics/", { date: form.date })
      setMsg("Snapshot created.")
      fetch()
    } catch (err) {
      const d = err.response?.data
      setError(typeof d==="string"?d: JSON.stringify(d))
    }
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-extrabold tracking-tight">Analytics Snapshots</h1>
        <p className="text-muted-foreground mt-1">Daily snapshots generated by APScheduler at 23:55. Admin can also create manually.</p>
      </div>

      {msg && <div className="text-sm text-emerald-700 bg-emerald-50 border border-emerald-200 rounded-xl p-3">{msg}</div>}
      {error && <div className="text-sm text-red-600 bg-red-50 border border-red-200 rounded-xl p-3 whitespace-pre-wrap">{error}</div>}

      <Card>
        <CardHeader><CardTitle className="text-base">Create snapshot</CardTitle></CardHeader>
        <CardContent>
          <form onSubmit={create} className="flex gap-3 items-end">
            <div>
              <Label>Date</Label>
              <Input type="date" value={form.date} onChange={e=>setForm({date:e.target.value})} className="mt-1.5" />
            </div>
            <Button type="submit" className="rounded-xl bg-zinc-900 hover:bg-black">Create</Button>
          </form>
        </CardContent>
      </Card>

      <Card>
        <CardHeader><CardTitle>History ({snapshots.length})</CardTitle></CardHeader>
        <CardContent>
          {snapshots.length===0 ? <p className="text-sm text-muted-foreground">No snapshots yet. Background job creates one daily.</p> :
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead className="text-xs text-muted-foreground border-b"><tr><th className="text-left py-2">Date</th><th className="text-left py-2">Users</th><th className="text-left py-2">Services</th><th className="text-left py-2">Bookings</th><th className="text-left py-2">Revenue</th></tr></thead>
                <tbody>
                  {snapshots.map(s=> (
                    <tr key={s.id} className="border-b last:border-0 hover:bg-zinc-50">
                      <td className="py-2 font-medium">{s.date}</td>
                      <td className="py-2">{s.total_users} ({s.total_customers}C / {s.total_providers}P)</td>
                      <td className="py-2">{s.total_services}</td>
                      <td className="py-2">{s.total_bookings} ({s.completed_bookings} ✅ {s.pending_bookings} ⏳)</td>
                      <td className="py-2 font-semibold">{s.total_revenue}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          }
        </CardContent>
      </Card>
    </div>
  )
}
